headers:
  - files:
      - "**/*.mp3"
      - "**/*.wav"
      - "**/*.ogg"
      - "**/*.gif"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
      - "**/*.woff2"
      - "**/*.otf"
      - "**/*.ttf"
      - "**/*.ico"
    values:
      Cache-Control: "public, max-age=15552000"